COMPILE_DEPS = CORE_DEPS + [
    "//apps/hierarchical-sync-master/proto:HierarchicalMasterServices",
    "//deps:com_google_protobuf_protobuf_java",
    ]
osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)