COMPILE_DEPS = CORE_DEPS + [
    "//apps/hierarchical-sync-master/proto:HierarchicalServices",
    "//apps/hierarchical-sync-master/proto:HierarchicalProto"
    ]
osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)